name: CI
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: install yarn
        run: npm install -g yarn
      - name: install dependencies
        run: yarn install
      - name: run test
        run: |
          yarn test
